import { useEffect, useState } from "react";
import { Alert, Autocomplete, Box, Button, Checkbox, Chip, CircularProgress, ListSubheader, MenuItem, Paper, Stack, Tab, Tabs, TextField, Typography } from "@mui/material";
import usePageTitle from "@platform/hooks/usePageTitle";
import { usePermissions } from "../../../../context/PermissionContext";
import { useAuth } from "../../../../context/AuthContext";
import { getWorkspaceConfiguration, listWorkspaces, saveWorkspaceAssignments, saveWorkspaceDashboard, searchWorkspacePreviewUsers, startLiveMode, updateWorkspace } from "../services/workspaceService";

const tabs = ["Settings", "Modules", "Navigation", "Buttons", "Widgets", "Dashboard", "Permissions", "Profiles", "Preview"];

export default function WorkspaceManagerPage() {
  usePageTitle("AUS | Workspace Manager");
  const {hasPermission}=usePermissions();
  const {user}=useAuth();
  const canConfigure=hasPermission("workspace.configure");
  const isSuperAdmin=String(user?.roleKey||user?.role||"").replace(/[\s_-]/g,"").toLowerCase()==="superadmin";
  const [workspaces,setWorkspaces]=useState([]),[workspaceId,setWorkspaceId]=useState(""),[config,setConfig]=useState(null),[tab,setTab]=useState(0),[loading,setLoading]=useState(true),[error,setError]=useState("");
  const [statusFilter,setStatusFilter]=useState("active");
  const [previewUserId,setPreviewUserId]=useState("");
  const [previewUsers,setPreviewUsers]=useState([]),[previewSearch,setPreviewSearch]=useState("");
  const [liveReason,setLiveReason]=useState("");
  const [dashboardId,setDashboardId]=useState(""),[defaultRoute,setDefaultRoute]=useState("");
  const [settings,setSettings]=useState({});
  useEffect(()=>{setLoading(true);listWorkspaces({status:statusFilter}).then(items=>{setWorkspaces(items);setWorkspaceId(current=>items.some(x=>String(x.WorkspaceId)===String(current))?current:(items[0]?.WorkspaceId||""));}).catch(e=>setError(e.response?.data?.message||e.message)).finally(()=>setLoading(false));},[statusFilter]);
  useEffect(()=>{if(!workspaceId)return;setLoading(true);getWorkspaceConfiguration(workspaceId).then(data=>{setConfig(data);setDashboardId(data.workspace?.DefaultDashboardId||"");setDefaultRoute(data.workspace?.DefaultRoute||"");const w=data.workspace||{};setSettings({workspaceKey:w.WorkspaceKey||"",workspaceName:w.WorkspaceName||"",workspaceCategory:w.WorkspaceCategory||"CORE",description:w.Description||"",icon:w.Icon||"",defaultRoute:w.DefaultRoute||"",visibilityStatusId:w.VisibilityStatusId,isDefault:Boolean(w.IsDefault),sortOrder:w.SortOrder||0,isActive:Boolean(w.IsActive)});}).catch(e=>setError(e.response?.data?.message||e.message)).finally(()=>setLoading(false));},[workspaceId]);
  useEffect(()=>{if(tab!==8)return;const timer=setTimeout(()=>searchWorkspacePreviewUsers(previewSearch).then(setPreviewUsers).catch(e=>setError(e.response?.data?.message||e.message)),250);return()=>clearTimeout(timer);},[previewSearch,tab]);
  const rows = tab===1?config?.modules:tab===2?config?.navigation:tab===3?config?.buttons:tab===4?config?.widgets:tab===5?config?.dashboards:tab===7?config?.profiles:null;
  const assignmentType=tab===1?"modules":tab===2?"navigation":tab===3?"buttons":tab===4?"widgets":tab===7?"profiles":null;
  const assignmentField={modules:"modules",navigation:"navigation",buttons:"buttons",widgets:"widgets",profiles:"profiles"}[assignmentType];
  const idField={modules:"ModuleId",navigation:"MenuId",buttons:"ButtonId",widgets:"WidgetId",profiles:"RoleId"}[assignmentType];
  const toggleAssignment=(index)=>setConfig(previous=>({...previous,[assignmentField]:previous[assignmentField].map((item,i)=>i===index?{...item,IsAssigned:!item.IsAssigned}:item)}));
  const updateAssignment=(index,field,value)=>setConfig(previous=>({...previous,[assignmentField]:previous[assignmentField].map((item,i)=>i===index?{...item,[field]:value}:item)}));
  const saveAssignments=async()=>{setLoading(true);setError("");try{const items=config[assignmentField].filter(x=>x.IsAssigned).map(x=>({id:x[idField],isVisible:true,isEnabled:x.IsEnabled!==false,isDefault:true,sortOrder:x.SortOrder,groupKey:x.GroupKey,groupName:x.GroupName,groupSortOrder:x.GroupSortOrder,parentMenuId:x.ParentMenuId}));setConfig(await saveWorkspaceAssignments(workspaceId,assignmentType,items));}catch(e){setError(e.response?.data?.message||e.message);}finally{setLoading(false);}};
  const saveSettings=async()=>{setLoading(true);setError("");try{await updateWorkspace(workspaceId,settings);setConfig(await getWorkspaceConfiguration(workspaceId));}catch(e){setError(e.response?.data?.message||e.message)}finally{setLoading(false)}};
  return <Stack spacing={2}>
    <Box><Typography variant="h4">Workspace Manager</Typography><Typography color="text.secondary">Presentation assignments never grant permissions.</Typography></Box>
    {error&&<Alert severity="error">{error}</Alert>}
    <Stack direction={{xs:"column",sm:"row"}} gap={2}><TextField select label="Status" value={statusFilter} onChange={e=>setStatusFilter(e.target.value)} sx={{width:180}}><MenuItem value="active">Active</MenuItem><MenuItem value="inactive">Inactive</MenuItem><MenuItem value="all">All</MenuItem></TextField><TextField select label="Workspace" value={workspaceId} onChange={e=>setWorkspaceId(e.target.value)} sx={{minWidth:320,maxWidth:520}}>{['CORE','ASSIGNMENT','LEGACY'].flatMap(category=>{const items=workspaces.filter(w=>w.WorkspaceCategory===category);return items.length?[<ListSubheader key={`${category}-header`}>{category==='CORE'?'CORE WORKSPACES':category==='ASSIGNMENT'?'ASSIGNMENT WORKSPACES':'LEGACY WORKSPACES'}</ListSubheader>,...items.map(w=><MenuItem key={w.WorkspaceId} value={w.WorkspaceId}>{w.WorkspaceName}{!w.IsActive?' · Inactive':''}</MenuItem>)]:[]})}</TextField></Stack>
    <Paper><Tabs value={tab} onChange={(_,v)=>setTab(v)} variant="scrollable">{tabs.map(x=><Tab key={x} label={x}/>)}</Tabs></Paper>
    {loading?<CircularProgress/>:<Paper sx={{p:3}}>
      {!canConfigure&&<Alert severity="info" sx={{mb:2}}>Read-only inspection mode. Configuration controls are disabled at the API layer.</Alert>}
      {tab===0&&<Stack spacing={2}><TextField disabled={!canConfigure} label="Workspace name" value={settings.workspaceName||""} onChange={e=>setSettings({...settings,workspaceName:e.target.value})}/><TextField disabled label="Workspace key" value={settings.workspaceKey||""}/><TextField disabled={!canConfigure} select label="Category" value={settings.workspaceCategory||"CORE"} onChange={e=>setSettings({...settings,workspaceCategory:e.target.value})}><MenuItem value="CORE">Core</MenuItem><MenuItem value="ASSIGNMENT">Assignment</MenuItem><MenuItem value="LEGACY">Legacy</MenuItem></TextField><TextField disabled={!canConfigure} multiline label="Description" value={settings.description||""} onChange={e=>setSettings({...settings,description:e.target.value})}/><TextField disabled={!canConfigure} type="number" label="Sort order" value={settings.sortOrder??0} onChange={e=>setSettings({...settings,sortOrder:Number(e.target.value)})}/><TextField disabled={!canConfigure} select label="Status" value={settings.isActive?"active":"inactive"} onChange={e=>setSettings({...settings,isActive:e.target.value==="active"})}><MenuItem value="active">Active</MenuItem><MenuItem value="inactive">Inactive</MenuItem></TextField><Chip label={settings.defaultRoute||"No landing route"} sx={{width:"fit-content"}}/>{canConfigure&&<Button variant="contained" onClick={saveSettings}>Save workspace settings</Button>}</Stack>}
      {tab===6&&<Alert severity="info">Workspace membership controls visibility only. Role permissions and user overrides are resolved by Permission Resolver.</Alert>}
      {tab===5&&<Stack spacing={2}><TextField disabled={!canConfigure} select label="Default dashboard" value={dashboardId} onChange={e=>setDashboardId(e.target.value)}><MenuItem value="">No dashboard</MenuItem>{(config?.dashboards||[]).map(item=><MenuItem key={item.DashboardId} value={item.DashboardId}>{item.DashboardName}</MenuItem>)}</TextField><TextField disabled={!canConfigure} select label="Default landing route" value={defaultRoute} onChange={e=>setDefaultRoute(e.target.value)}>{(config?.navigation||[]).filter(item=>item.IsAssigned&&item.Route).map(item=><MenuItem key={item.MenuId} value={item.Route}>{item.MenuName} — {item.Route}</MenuItem>)}</TextField>{canConfigure&&<Button variant="contained" onClick={async()=>{setLoading(true);try{const data=await saveWorkspaceDashboard(workspaceId,dashboardId,defaultRoute);setConfig(data);}catch(e){setError(e.response?.data?.message||e.message);}finally{setLoading(false);}}}>Save dashboard and landing route</Button>}</Stack>}
      {assignmentType&&canConfigure&&<Button sx={{mb:2}} variant="contained" onClick={saveAssignments}>Save {assignmentType} assignments</Button>}
      {tab===8&&<Stack spacing={2}><Alert severity="info">Configuration Preview is read-only and does not impersonate a user.</Alert><Button disabled={!workspaceId} variant="contained" onClick={()=>window.open(`/super-admin/workspace-preview?workspaceId=${encodeURIComponent(workspaceId)}`,"_blank","noopener,noreferrer")}>Open workspace configuration preview</Button>{isSuperAdmin&&<><Alert severity="error">Live Mode is separate from Preview and performs real actions with a target user’s actual permissions. All activity is audited.</Alert><Autocomplete options={previewUsers} value={previewUsers.find(item=>String(item.UserId)===String(previewUserId))||null} onInputChange={(_,value,reason)=>{if(reason==="input")setPreviewSearch(value)}} onChange={(_,value)=>setPreviewUserId(value?.UserId||"")} getOptionLabel={item=>`${item.FullName} (${item.EmployeeId}) — ${item.RoleName}`} renderInput={params=><TextField {...params} label="Live Mode target user"/>}/><TextField label="Required troubleshooting reason" value={liveReason} onChange={e=>setLiveReason(e.target.value)}/><Button color="error" variant="contained" disabled={!previewUserId||liveReason.trim().length<10} onClick={async()=>{if(!window.confirm("Enter Live Mode as this user? Real permitted actions will be possible."))return;try{const result=await startLiveMode(previewUserId,liveReason);window.open(`/live-workspace#liveToken=${encodeURIComponent(result.token)}`,"_blank","noopener,noreferrer");}catch(e){setError(e.response?.data?.message||e.message);}}}>Enter Live Mode</Button></>}</Stack>}
      {Array.isArray(rows)&&tab!==5&&tab!==8&&<Stack spacing={1}>{rows.length?rows.map((row,index)=><Paper variant="outlined" sx={{p:1.5}} key={row.ModuleId||row.MenuId||row.ButtonId||row.WidgetId||row.DashboardId||row.RoleId||index}>{assignmentType&&<Checkbox checked={Boolean(row.IsAssigned)} onChange={()=>toggleAssignment(index)}/>}<Typography component="span">{row.ModuleName||row.MenuName||row.ButtonName||row.WidgetName||row.DashboardName||row.RoleName}</Typography>{assignmentType&&assignmentType!=="profiles"&&<TextField size="small" type="number" label="Sort" value={row.SortOrder??0} onChange={e=>updateAssignment(index,"SortOrder",Number(e.target.value))} sx={{width:100,ml:2}}/>}{assignmentType==="navigation"&&<><TextField size="small" label="Group" value={row.GroupName||"Main"} onChange={e=>updateAssignment(index,"GroupName",e.target.value)} sx={{width:180,ml:1}}/><TextField size="small" type="number" label="Group sort" value={row.GroupSortOrder??0} onChange={e=>updateAssignment(index,"GroupSortOrder",Number(e.target.value))} sx={{width:120,ml:1}}/></>}<Typography variant="caption" display="block" color="text.secondary">{row.BaseRoute||row.Route||row.ModuleKey||row.RoleKey||"Configured record"}</Typography></Paper>):<Typography color="text.secondary">No supported records assigned.</Typography>}</Stack>}
    </Paper>}
  </Stack>;
}
