const service=require("../services/accessLevelService");
const asyncHandler=require("../../../shared/helpers/asyncHandler");
const {sendSuccess}=require("../../../shared/helpers/apiResponse");
const activityLogger=require("../../audit/services/activityLogger");
const audit=(req,action,oldValue,newValue,id)=>activityLogger.log({moduleKey:"USER_ACCESS",actionType:action,entityType:"AccessLevel",entityId:id,title:`Access level ${action.toLowerCase()}`,oldValue,newValue,user:req.user,ipAddress:req.ip});
exports.list=asyncHandler(async(req,res)=>sendSuccess(res,"Access levels loaded successfully.",await service.list(req.query)));
exports.get=asyncHandler(async(req,res)=>sendSuccess(res,"Access level loaded successfully.",await service.getById(req.params.id)));
exports.create=asyncHandler(async(req,res)=>{const data=await service.create(req.body);await audit(req,"CREATE",null,data,data.AccessLevelId);return sendSuccess(res,"Access level created successfully.",data,201);});
exports.update=asyncHandler(async(req,res)=>{const oldValue=await service.getById(req.params.id);const data=await service.update(req.params.id,req.body);await audit(req,"UPDATE",oldValue,data,data.AccessLevelId);return sendSuccess(res,"Access level updated successfully.",data);});
exports.activate=asyncHandler(async(req,res)=>{const oldValue=await service.getById(req.params.id);const data=await service.setActive(req.params.id,true);await audit(req,"ACTIVATE",oldValue,data,data.AccessLevelId);return sendSuccess(res,"Access level activated successfully.",data);});
exports.deactivate=asyncHandler(async(req,res)=>{const oldValue=await service.getById(req.params.id);const data=await service.setActive(req.params.id,false);await audit(req,"DEACTIVATE",oldValue,data,data.AccessLevelId);return sendSuccess(res,"Access level deactivated successfully.",data);});
exports.remove=asyncHandler(async(req,res)=>{const data=await service.remove(req.params.id);await audit(req,"DELETE",data,null,data.AccessLevelId);return sendSuccess(res,"Access level deleted successfully.",data);});
