SET XACT_ABORT ON;

BEGIN TRANSACTION;

ALTER TABLE dbo.StaffImportBatches
ADD UpdateRows int NOT NULL DEFAULT 0;

ALTER TABLE dbo.StaffImportBatches
ADD IgnoredRows int NOT NULL DEFAULT 0;

COMMIT TRANSACTION;
