/* =========================================================
   IT Asset Action Constants
========================================================= */

module.exports = {
  CREATED: "ASSET_CREATED",
  UPDATED: "ASSET_UPDATED",
  DELETED: "ASSET_DELETED",
  ASSIGNED: "ASSET_ASSIGNED",
  RETURNED: "ASSET_RETURNED",
  STATUS_CHANGED: "ASSET_STATUS_CHANGED",
  MAINTENANCE_STARTED: "ASSET_MAINTENANCE_STARTED",
  MAINTENANCE_COMPLETED: "ASSET_MAINTENANCE_COMPLETED",
  TRANSFER_REQUESTED: "ASSET_TRANSFER_REQUESTED",
  TRANSFER_APPROVED: "ASSET_TRANSFER_APPROVED",
  DISPOSED: "ASSET_DISPOSED",
  NOTE_ADDED: "ASSET_NOTE_ADDED",
  IMPORTED: "ASSET_IMPORTED",
};