import {useCallback,useEffect,useState} from "react";
import {Alert,Checkbox,FormControlLabel,Stack,TextField} from "@mui/material";
import {AppButton,AppChip,AppDataTable,AppDialog,AppPageHeader,AppToolbar} from "@ui";
import {accessLevelApi,unwrap} from "../api/userAccessApi";
const empty={accessLevelKey:"",accessLevelName:"",displayName:"",description:"",sortOrder:0,isActive:true};
export default function AccessLevelsPage(){
 const [rows,setRows]=useState([]),[total,setTotal]=useState(0),[page,setPage]=useState(0),[pageSize,setPageSize]=useState(10),[search,setSearch]=useState(""),[status,setStatus]=useState(""),[loading,setLoading]=useState(true),[error,setError]=useState(""),[open,setOpen]=useState(false),[editing,setEditing]=useState(null),[form,setForm]=useState(empty);
 const load=useCallback(async()=>{try{setLoading(true);setError("");const body=unwrap(await accessLevelApi.list({page:page+1,pageSize,search,status}));setRows(body.items||[]);setTotal(body.totalRows||0);}catch(e){setError(e?.response?.data?.message||"Unable to load access levels.");}finally{setLoading(false)}},[page,pageSize,search,status]);
  
 useEffect(()=>{load()},[load]); const edit=(r=null)=>{setEditing(r);setForm(r?{accessLevelKey:r.AccessLevelKey,accessLevelName:r.AccessLevelName,displayName:r.DisplayName,description:r.Description||"",sortOrder:r.SortOrder,isActive:r.IsActive}:empty);setOpen(true)};
 const save=async()=>{try{if(editing)await accessLevelApi.update(editing.AccessLevelId,form);else await accessLevelApi.create(form);setOpen(false);await load()}catch(e){setError(e?.response?.data?.message||"Unable to save access level.")}};
 const toggle=async r=>{if(r.IsActive)await accessLevelApi.deactivate(r.AccessLevelId);else await accessLevelApi.activate(r.AccessLevelId);await load()};const remove=async r=>{if(!r.IsSystemLevel&&window.confirm("Delete this access level?")){try{await accessLevelApi.remove(r.AccessLevelId);await load()}catch(e){setError(e?.response?.data?.message||"Unable to delete access level.")}}};
 const columns=[{field:"DisplayName",headerName:"Access Level"},{field:"AccessLevelKey",headerName:"Key"},{field:"Description",headerName:"Description"},{field:"IsActive",headerName:"Status",render:r=><AppChip label={r.IsActive?"Active":"Inactive"} status={r.IsActive?"success":"inactive"}/>},{field:"actions",headerName:"Actions",render:r=><Stack direction="row" spacing={1}><AppButton buttonKey="ACCESS_LEVEL_UPDATE" size="small" variant="outlined" onClick={()=>edit(r)}>View / Edit</AppButton><AppButton buttonKey="ACCESS_LEVEL_UPDATE" size="small" variant="outlined" onClick={()=>toggle(r)}>{r.IsActive?"Deactivate":"Activate"}</AppButton>{!r.IsSystemLevel&&<AppButton buttonKey="ACCESS_LEVEL_DELETE" size="small" color="error" variant="outlined" onClick={()=>remove(r)}>Delete</AppButton>}</Stack>}];
 return <Stack spacing={3}><AppPageHeader title="Access Levels" subtitle="Manage enterprise access hierarchy." actions={<AppButton onClick={()=>edit()}>Add Access Level</AppButton>}/><AppToolbar searchValue={search} onSearchChange={e=>{setSearch(e.target.value);setPage(0)}}><TextField select SelectProps={{native:true}} size="small" label="Status" value={status} onChange={e=>{setStatus(e.target.value);setPage(0)}}><option value="">All</option><option value="active">Active</option><option value="inactive">Inactive</option></TextField></AppToolbar>{error&&<Alert severity="error">{error}</Alert>}<AppDataTable rows={rows} columns={columns} loading={loading} page={page} rowsPerPage={pageSize} totalRows={total} onPageChange={(_,v)=>setPage(v)} onRowsPerPageChange={e=>{setPageSize(Number(e.target.value));setPage(0)}} getRowId={r=>r.AccessLevelId}/><AppDialog open={open} title={editing?"Edit Access Level":"Add Access Level"} onClose={()=>setOpen(false)} onPrimary={save} disablePrimary={!form.accessLevelKey||!form.accessLevelName||!form.displayName}><TextField label="Key" value={form.accessLevelKey} disabled={Boolean(editing?.IsSystemLevel)} onChange={e=>setForm({...form,accessLevelKey:e.target.value})}/><TextField label="Name" value={form.accessLevelName} disabled={Boolean(editing?.IsSystemLevel)} onChange={e=>setForm({...form,accessLevelName:e.target.value})}/><TextField label="Display Name" value={form.displayName} onChange={e=>setForm({...form,displayName:e.target.value})}/><TextField label="Description" multiline value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/><TextField label="Sort Order" type="number" value={form.sortOrder} onChange={e=>setForm({...form,sortOrder:Number(e.target.value)})}/><FormControlLabel control={<Checkbox checked={form.isActive} onChange={e=>setForm({...form,isActive:e.target.checked})}/>} label="Active"/></AppDialog></Stack>;
}
