import {useCallback,useEffect,useMemo,useState} from "react";
import {Alert,Checkbox,FormControlLabel,MenuItem,Stack,TextField} from "@mui/material";
import {AppButton,AppChip,AppDataTable,AppDialog,AppPageHeader,AppToolbar} from "@ui";
import {assignmentApi,unwrap} from "../api/userAccessApi";
const blank={userId:"",assignmentTypeId:"",academicYearId:"",departmentId:"",sectionId:"",subjectId:"",yearLevelId:"",classId:"",roomId:"",startDate:"",endDate:"",isPrimary:false};
export default function UserAssignmentsPage(){const [rows,setRows]=useState([]),[lookups,setLookups]=useState({}),[total,setTotal]=useState(0),[page,setPage]=useState(0),[pageSize,setPageSize]=useState(10),[search,setSearch]=useState(""),[status,setStatus]=useState(""),[type,setType]=useState(""),[loading,setLoading]=useState(true),[error,setError]=useState(""),[open,setOpen]=useState(false),[editing,setEditing]=useState(null),[form,setForm]=useState(blank);
 const load=useCallback(async()=>{try{setLoading(true);const body=unwrap(await assignmentApi.list({page:page+1,pageSize,search,status,assignmentTypeId:type}));setRows(body.items||[]);setTotal(body.totalRows||0)}catch(e){setError(e?.response?.data?.message||"Unable to load assignments.")}finally{setLoading(false)}},[page,pageSize,search,status,type]);
  
 useEffect(()=>{load()},[load]);useEffect(()=>{assignmentApi.lookups().then(r=>setLookups(unwrap(r))).catch(()=>setError("Unable to load assignment lookups."))},[]);
 const sections=useMemo(()=>lookups.sections||[],[lookups.sections]);const edit=r=>{setEditing(r||null);setForm(r?{userId:r.UserId,assignmentTypeId:r.AssignmentTypeId,academicYearId:r.AcademicYearId||"",departmentId:r.DepartmentId||"",sectionId:r.SectionId||"",subjectId:r.SubjectId||"",yearLevelId:r.YearLevelId||"",classId:r.ClassId||"",roomId:r.RoomId||"",startDate:r.StartDate?.slice(0,10)||"",endDate:r.EndDate?.slice(0,10)||"",isPrimary:r.IsPrimary}:blank);setOpen(true)};
 const payload=()=>Object.fromEntries(Object.entries({...form}).map(([k,v])=>[k,v===""?null:v]));const save=async()=>{try{const data=payload();if(editing)await assignmentApi.update(form.userId,editing.UserAssignmentId,data);else await assignmentApi.create(form.userId,data);setOpen(false);await load()}catch(e){setError(e?.response?.data?.message||"Unable to save assignment.")}};
 const action=async(r,kind)=>{if(kind==="primary")await assignmentApi.primary(r.UserId,r.UserAssignmentId);else if(r.IsActive)await assignmentApi.deactivate(r.UserId,r.UserAssignmentId);else await assignmentApi.activate(r.UserId,r.UserAssignmentId);await load()};const columns=[{field:"FullName",headerName:"User"},{field:"EmployeeId",headerName:"Employee ID"},{field:"AssignmentName",headerName:"Assignment"},{field:"AcademicYearName",headerName:"Academic Year"},{field:"DepartmentName",headerName:"Department"},{field:"IsPrimary",headerName:"Primary",render:r=>r.IsPrimary?"Yes":"No"},{field:"IsActive",headerName:"Status",render:r=><AppChip label={r.IsActive?"Active":"Inactive"} status={r.IsActive?"success":"inactive"}/>},{field:"actions",headerName:"Actions",render:r=><Stack direction="row" spacing={1}><AppButton size="small" variant="outlined" onClick={()=>edit(r)}>View / Edit</AppButton>{r.IsActive&&!r.IsPrimary&&<AppButton size="small" variant="outlined" onClick={()=>action(r,"primary")}>Primary</AppButton>}<AppButton size="small" variant="outlined" onClick={()=>action(r,"toggle")}>{r.IsActive?"Deactivate":"Activate"}</AppButton></Stack>}];
 const select=(key,label,items,id,name)=><TextField select label={label} value={form[key]??""} onChange={e=>setForm({...form,[key]:e.target.value})}>{items.map(x=><MenuItem key={x[id]} value={x[id]}>{x[name]}</MenuItem>)}</TextField>;
 return <Stack spacing={3}><AppPageHeader title="User Assignments" subtitle="Assign responsibilities using registered assignment types and retain assignment history." actions={<AppButton onClick={()=>edit(null)}>Add Assignment</AppButton>}/><AppToolbar searchValue={search} onSearchChange={e=>{setSearch(e.target.value);setPage(0)}}><TextField select SelectProps={{native:true}} size="small" label="Status" value={status} onChange={e=>setStatus(e.target.value)}><option value="">All</option><option value="active">Active</option><option value="inactive">Inactive</option></TextField><TextField select SelectProps={{native:true}} size="small" label="Type" value={type} onChange={e=>setType(e.target.value)}><option value="">All</option>{(lookups.assignmentTypes||[]).map(x=><option key={x.AssignmentTypeId} value={x.AssignmentTypeId}>{x.AssignmentName}</option>)}</TextField></AppToolbar>{error&&<Alert severity="error">{error}</Alert>}<AppDataTable rows={rows} columns={columns} loading={loading} page={page} rowsPerPage={pageSize} totalRows={total} onPageChange={(_,v)=>setPage(v)} onRowsPerPageChange={e=>setPageSize(Number(e.target.value))} getRowId={r=>r.UserAssignmentId}/><AppDialog open={open} title={editing?"Edit Assignment":"Add Assignment"} onClose={()=>setOpen(false)} onPrimary={save} disablePrimary={!form.userId||!form.assignmentTypeId||!form.academicYearId}>{select("userId","User",lookups.users||[],"UserId","FullName")}{select("assignmentTypeId","Assignment Type",lookups.assignmentTypes||[],"AssignmentTypeId","AssignmentName")}{select("academicYearId","Academic Year",lookups.academicYears||[],"AcademicYearId","AcademicYearName")}{select("departmentId","Department",lookups.departments||[],"DepartmentId","DepartmentName")}{select("sectionId","Section",sections,"SectionId","SectionName")}<TextField type="date" label="Start Date" slotProps={{inputLabel:{shrink:true}}} value={form.startDate} onChange={e=>setForm({...form,startDate:e.target.value})}/><TextField type="date" label="End Date" slotProps={{inputLabel:{shrink:true}}} value={form.endDate} onChange={e=>setForm({...form,endDate:e.target.value})}/><FormControlLabel control={<Checkbox checked={form.isPrimary} onChange={e=>setForm({...form,isPrimary:e.target.checked})}/>} label="Primary assignment"/></AppDialog></Stack>}
