import{useCallback,useEffect,useMemo,useState}from"react";import{Alert,Checkbox,FormControlLabel,MenuItem,Stack,TextField,Typography}from"@mui/material";import{AppButton,AppChip,AppDataTable,AppDialog,AppPageHeader,AppToolbar}from"@ui";import{assignmentApi,unwrap}from"../api/userAccessApi";
const blank={userId:"",assignmentTypeId:"",academicYearId:"",startDate:"",endDate:"",isPrimary:false,scopes:[]};
const optionMap={School:["schools","SchoolId","SchoolName"],Department:["departments","DepartmentId","DepartmentName"],Section:["sections","SectionId","SectionName"],YearGroup:["yearLevels","YearLevelId","YearLevelName"],Subject:["subjects","SubjectId","SubjectName"],Location:["locations","LocationId","LocationName"],Class:["classes","ClassId","ClassName"],Room:["rooms","RoomId","RoomName"]};
export default function UserAssignmentsPage(){const[rows,setRows]=useState([]),[lookups,setLookups]=useState({}),[total,setTotal]=useState(0),[page,setPage]=useState(0),[pageSize,setPageSize]=useState(10),[search,setSearch]=useState(""),[status,setStatus]=useState(""),[loading,setLoading]=useState(true),[error,setError]=useState(""),[open,setOpen]=useState(false),[editing,setEditing]=useState(null),[form,setForm]=useState(blank);
const load=useCallback(async()=>{try{setLoading(true);const b=unwrap(await assignmentApi.list({page:page+1,pageSize,search,status}));setRows(b.items||[]);setTotal(b.totalRows||0)}catch(e){setError(e?.response?.data?.message||"Unable to load assignments.")}finally{setLoading(false)}},[page,pageSize,search,status]);useEffect(()=>{load()},[load]);useEffect(()=>{assignmentApi.lookups().then(r=>setLookups(unwrap(r))).catch(()=>setError("Unable to load assignment lookups."))},[]);
const rules=useMemo(()=>(lookups.assignmentTypeScopeTypes||[]).filter(x=>String(x.AssignmentTypeId)===String(form.assignmentTypeId)),[lookups.assignmentTypeScopeTypes,form.assignmentTypeId]);
const edit=row=>{setEditing(row||null);setForm(row?{userId:row.UserId,assignmentTypeId:row.AssignmentTypeId,academicYearId:row.AcademicYearId||"",startDate:row.StartDate?.slice(0,10)||"",endDate:row.EndDate?.slice(0,10)||"",isPrimary:Boolean(row.IsPrimary),scopes:(row.Scopes||[]).map(s=>({scopeType:s.ScopeType,scopeEntityId:s.ScopeEntityId}))}:blank);setOpen(true)};
const setScope=(scopeType,ids)=>setForm(p=>({...p,scopes:[...p.scopes.filter(s=>s.scopeType!==scopeType),...ids.map(id=>({scopeType,scopeEntityId:Number(id)}))]}));
const save=async()=>{try{const payload={...form,userId:undefined};if(editing)await assignmentApi.update(form.userId,editing.UserAssignmentId,payload);else await assignmentApi.create(form.userId,payload);setOpen(false);await load()}catch(e){setError(e?.response?.data?.message||"Unable to save assignment.")}};
const action=async(r,k)=>{if(k==="primary")await assignmentApi.primary(r.UserId,r.UserAssignmentId);else if(r.IsActive)await assignmentApi.deactivate(r.UserId,r.UserAssignmentId);else await assignmentApi.activate(r.UserId,r.UserAssignmentId);await load()};
const columns=[{field:"FullName",headerName:"User"},{field:"AssignmentName",headerName:"Assignment"},{field:"Scopes",headerName:"Organizational Scopes",render:r=><Typography>{(r.Scopes||[]).map(s=>s.ScopeName).join(", ")||"No scope"}</Typography>},{field:"IsPrimary",headerName:"Primary Workspace",render:r=>r.IsPrimary?"Yes":"No"},{field:"IsActive",headerName:"Status",render:r=><AppChip label={r.IsActive?"Active":"Inactive"} status={r.IsActive?"success":"inactive"}/>},{field:"actions",headerName:"Actions",render:r=><Stack direction="row" spacing={1}><AppButton buttonKey="USER_ASSIGNMENT_UPDATE" onClick={()=>edit(r)}>Edit</AppButton>{r.IsActive&&!r.IsPrimary&&<AppButton buttonKey="USER_ASSIGNMENT_UPDATE" onClick={()=>action(r,"primary")}>Set Primary</AppButton>}<AppButton buttonKey="USER_ASSIGNMENT_DELETE" onClick={()=>action(r,"toggle")}>{r.IsActive?"Deactivate":"Activate"}</AppButton></Stack>}];
const select=(key,label,items,id,name)=><TextField select label={label} value={form[key]} onChange={e=>setForm(p=>({...p,[key]:e.target.value,...(key==="assignmentTypeId"?{scopes:[]}:{})}))}>{items.map(x=><MenuItem key={x[id]} value={x[id]}>{x[name]}</MenuItem>)}</TextField>;
return <Stack spacing={3}><AppPageHeader title="User Assignments" subtitle="One assignment may cover multiple organizational scopes." actions={<AppButton buttonKey="USER_ASSIGNMENT_CREATE" onClick={()=>edit(null)}>Add Assignment</AppButton>}/><AppToolbar searchValue={search} onSearchChange={e=>setSearch(e.target.value)}><TextField select size="small" label="Status" value={status} onChange={e=>setStatus(e.target.value)}><MenuItem value="">All</MenuItem><MenuItem value="active">Active</MenuItem><MenuItem value="inactive">Inactive</MenuItem></TextField></AppToolbar>{error&&<Alert severity="error">{error}</Alert>}<AppDataTable rows={rows} columns={columns} loading={loading} page={page} rowsPerPage={pageSize} totalRows={total} onPageChange={(_,v)=>setPage(v)} onRowsPerPageChange={e=>setPageSize(Number(e.target.value))} getRowId={r=>r.UserAssignmentId}/><AppDialog open={open} title={editing?"Edit Assignment":"Add Assignment"} onClose={()=>setOpen(false)} onPrimary={save} disablePrimary={!form.userId||!form.assignmentTypeId||!form.academicYearId}>{select("userId","User",lookups.users||[],"UserId","FullName")}{select("assignmentTypeId","Assignment Type",lookups.assignmentTypes||[],"AssignmentTypeId","AssignmentName")}{select("academicYearId","Academic Year",lookups.academicYears||[],"AcademicYearId","AcademicYearName")}{rules.map(rule=>{const m=optionMap[rule.ScopeType],items=lookups[m?.[0]]||[],value=form.scopes.filter(s=>s.scopeType===rule.ScopeType).map(s=>s.scopeEntityId);return <TextField key={rule.ScopeType} select label={`${rule.ScopeType}${rule.IsRequired?" *":""}`} value={value} onChange={e=>setScope(rule.ScopeType,e.target.value)} slotProps={{select:{multiple:true}}}>{items.map(x=><MenuItem key={x[m[1]]} value={x[m[1]]}>{x[m[2]]}</MenuItem>)}</TextField>})}<TextField type="date" label="Start Date" slotProps={{inputLabel:{shrink:true}}} value={form.startDate} onChange={e=>setForm(p=>({...p,startDate:e.target.value}))}/><TextField type="date" label="End Date" slotProps={{inputLabel:{shrink:true}}} value={form.endDate} onChange={e=>setForm(p=>({...p,endDate:e.target.value}))}/><FormControlLabel control={<Checkbox checked={form.isPrimary} onChange={e=>setForm(p=>({...p,isPrimary:e.target.checked}))}/>} label="Primary Workspace Assignment"/></AppDialog></Stack>}
