import {useState} from "react";
import {Alert,Avatar,Button,Card,CardContent,Dialog,DialogActions,DialogContent,DialogTitle,Divider,Grid,Stack,TextField,Typography} from "@mui/material";
import {useNavigate} from "react-router-dom";
import {useAuth} from "../../../context/AuthContext";
import {changeCurrentPassword} from "../../../services/authService";

export default function Profile(){
  const{user,logout}=useAuth(),navigate=useNavigate(),[open,setOpen]=useState(false),[form,setForm]=useState({currentPassword:"",newPassword:"",confirmPassword:""}),[message,setMessage]=useState(null),[busy,setBusy]=useState(false);
  const fullName=user?.fullName||"Unknown User",assignments=user?.assignmentScopes||[],workspace=user?.defaultWorkspaceName||user?.defaultWorkspaceRoute||"Not assigned";
  const doLogout=()=>{logout();navigate("/login",{replace:true});};
  const changePassword=async()=>{if(form.newPassword.length<8){setMessage({severity:"error",text:"Password must be at least 8 characters."});return;}if(form.newPassword!==form.confirmPassword){setMessage({severity:"error",text:"New password confirmation does not match."});return;}setBusy(true);try{await changeCurrentPassword({currentPassword:form.currentPassword,newPassword:form.newPassword});setMessage({severity:"success",text:"Password changed successfully."});setForm({currentPassword:"",newPassword:"",confirmPassword:""});setOpen(false);}catch(e){setMessage({severity:"error",text:e.response?.data?.message||e.message});}finally{setBusy(false)}};
  return <Stack spacing={3} sx={{maxWidth:1000,mx:"auto"}}>
    <Stack direction={{xs:"column",sm:"row"}} justifyContent="space-between" gap={2}><Stack direction="row" spacing={2} alignItems="center"><Avatar sx={{width:72,height:72,fontSize:28}}>{fullName.split(/\s+/).map(x=>x[0]).slice(0,2).join("")}</Avatar><div><Typography variant="h4" fontWeight={800}>{fullName}</Typography><Typography color="text.secondary">{user?.roleName||user?.role}</Typography></div></Stack><Stack direction="row" gap={1} alignItems="center"><Button variant="outlined" onClick={()=>setOpen(true)}>Change Password</Button><Button color="error" variant="contained" onClick={doLogout}>Logout</Button></Stack></Stack>
    {message&&<Alert severity={message.severity} onClose={()=>setMessage(null)}>{message.text}</Alert>}
    <Card><CardContent><Typography variant="h6" gutterBottom>Account</Typography><Grid container spacing={2}>{[["Employee ID",user?.employeeId],["Email",user?.email],["Role",user?.roleName||user?.role],["Active Workspace",workspace]].map(([label,value])=><Grid item xs={12} sm={6} key={label}><Typography variant="caption" color="text.secondary">{label}</Typography><Typography fontWeight={700}>{value||"N/A"}</Typography></Grid>)}</Grid></CardContent></Card>
    <Card><CardContent><Typography variant="h6">Assignments</Typography><Divider sx={{my:1.5}}/>{assignments.length?<Stack spacing={1}>{assignments.map((a,i)=><Stack key={`${a.UserAssignmentId}-${a.ScopeType}-${a.ScopeEntityId}-${i}`} direction={{xs:"column",sm:"row"}} justifyContent="space-between"><Typography fontWeight={700}>{a.AssignmentName||a.AssignmentKey}</Typography><Typography color="text.secondary">{a.ScopeType?`${a.ScopeType} #${a.ScopeEntityId}`:"Workspace assignment"}{a.IsPrimary?" · Primary":""}</Typography></Stack>)}</Stack>:<Typography color="text.secondary">No active assignments.</Typography>}</CardContent></Card>
    <Dialog open={open} onClose={()=>!busy&&setOpen(false)} fullWidth maxWidth="xs"><DialogTitle>Change Password</DialogTitle><DialogContent><Stack spacing={2} sx={{pt:1}}><TextField type="password" label="Current password" value={form.currentPassword} onChange={e=>setForm({...form,currentPassword:e.target.value})}/><TextField type="password" label="New password" helperText="At least 8 characters." value={form.newPassword} onChange={e=>setForm({...form,newPassword:e.target.value})}/><TextField type="password" label="Confirm new password" value={form.confirmPassword} onChange={e=>setForm({...form,confirmPassword:e.target.value})}/></Stack></DialogContent><DialogActions><Button onClick={()=>setOpen(false)} disabled={busy}>Cancel</Button><Button variant="contained" onClick={changePassword} disabled={busy||!form.currentPassword||!form.newPassword}>{busy?"Changing...":"Change Password"}</Button></DialogActions></Dialog>
  </Stack>;
}
